import { existsSync, readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";

import { join } from "pathe";

import { EJECTED_CONFIG_HEADER } from "../astro/templates.ts";
import { packageRoot } from "../core/package-root.ts";
import { commandsFor, detectProjectPackageManager } from "./init/scaffold.ts";
import type { PackageManager } from "./init/scaffold.ts";
import { logger } from "./log.ts";

/** A JSON value, as `JSON.parse` of a manifest can return. */
type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

/** The slice of package.json the rewrite touches; the rest rides along. */
interface PackageManifest {
  [key: string]: JsonValue | undefined;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
}

/** Package name → the semver range to depend on it at. */
export interface DependencyRanges {
  [name: string]: string;
}

/**
 * The version range Blume itself uses for each package it depends on or
 * accepts as a peer, plus `blume` at the installed version — what an ejected
 * app should pin so it keeps building against the same majors.
 */
export const blumeDependencyRanges = (): DependencyRanges => {
  // SAFETY: blume's own package.json, which declares its version and both
  // dependency maps; nothing else is read.
  const manifest = JSON.parse(
    readFileSync(join(packageRoot(), "package.json"), "utf-8")
  ) as {
    dependencies: Record<string, string>;
    peerDependencies: Record<string, string>;
    version: string;
  };
  return {
    ...manifest.peerDependencies,
    ...manifest.dependencies,
    blume: `^${manifest.version}`,
  };
};

/** Whether the manifest already lists `name` in any dependency field. */
const declares = (pkg: PackageManifest, name: string): boolean =>
  [
    pkg.dependencies,
    pkg.devDependencies,
    pkg.optionalDependencies,
    pkg.peerDependencies,
  ].some((field) => field !== undefined && Object.hasOwn(field, name));

/**
 * Point the project's package.json at the ejected app. Its scripts run Astro
 * directly: after an eject the Blume CLI no longer manages the runtime, so
 * scaffolded scripts like `"dev": "blume dev"` would rebuild the removed
 * `.blume` tree instead of serving the ejected app. And every package the
 * ejected app imports by bare name (`dependencies`, from `eject()`) that the
 * project doesn't list yet becomes a dependency at the range Blume itself
 * uses (`ranges`).
 *
 * Returns the names it added, so the caller can ask for an install. A missing
 * or unreadable package.json is left alone.
 */
export const updatePackageScripts = async (
  root: string,
  dependencies: string[] = [],
  ranges: DependencyRanges = blumeDependencyRanges()
): Promise<string[]> => {
  const pkgPath = join(root, "package.json");
  let pkg: PackageManifest;
  try {
    pkg = JSON.parse(await readFile(pkgPath, "utf-8"));
  } catch {
    return [];
  }
  const scripts = pkg.scripts ?? {};
  pkg.scripts = {
    ...scripts,
    build: "astro build",
    dev: "astro dev",
    preview: "astro preview",
  };
  const added = dependencies.filter((name) => !declares(pkg, name));
  if (added.length > 0) {
    // Sorted, the way package managers write the field.
    pkg.dependencies = Object.fromEntries(
      Object.entries({
        ...pkg.dependencies,
        ...Object.fromEntries(added.map((name) => [name, ranges[name] ?? "*"])),
      }).toSorted(([a], [b]) => (a < b ? -1 : 1))
    );
  }
  await writeFile(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf-8");
  return added;
};

/**
 * The first line Blume 1's `blume eject` wrote into the ejected
 * `astro.config.mjs` — the hidden runtime's own header, carried over. Blume 2's
 * hidden runtime keeps it under `.blume/`, never at the project root, so a root
 * config that opens with it is an app Blume 1 ejected.
 */
const BLUME_1_EJECTED_CONFIG_HEADER =
  "// Generated by Blume. Do not edit; this file is recreated on each run.";

/**
 * Whether `root` holds an app `blume eject` already wrote: a root
 * `astro.config.mjs` whose first line is eject's header, or the header Blume 1
 * ejected with. The header is the only signal: a Blume project may keep its own
 * `astro.config.mjs` and a codegen `src/generated/` folder beside its content,
 * and neither makes it an ejected app.
 */
export const isEjectedProject = (root: string): boolean => {
  const config = join(root, "astro.config.mjs");
  if (!existsSync(config)) {
    return false;
  }
  const source = readFileSync(config, "utf-8");
  return (
    source.startsWith(EJECTED_CONFIG_HEADER) ||
    source.startsWith(BLUME_1_EJECTED_CONFIG_HEADER)
  );
};

/** The Blume commands that run the hidden `.blume/` copy of the site. */
export type RuntimeCommand = "build" | "check" | "dev" | "preview" | "sync";

/**
 * What an ejected app runs in place of each {@link RuntimeCommand}: its own
 * `dev`/`build`/`preview` scripts (eject writes them), or Astro's CLI for the
 * check and the content sync.
 */
const ejectedEquivalent = (
  pm: PackageManager,
  command: RuntimeCommand
): string => {
  const { build, dev, exec } = commandsFor(pm);
  return {
    build,
    check: `${exec} astro check`,
    dev,
    // Spelled like `dev`: npm runs a custom script only through `run`.
    preview: pm === "npm" ? "npm run preview" : `${pm} preview`,
    sync: `${exec} astro sync`,
  }[command];
};

/**
 * Stop a command that works on the hidden runtime in an ejected app. `dev`,
 * `build`, `check`, and `sync` would regenerate `.blume/` from
 * `blume.config.ts` and run that hidden copy, ignoring every edit made to the
 * app since eject, and `preview` would look for that copy's build; point at
 * the app's own command under the project's package manager instead.
 */
export const refuseIfEjected = async (
  root: string,
  command: RuntimeCommand
): Promise<void> => {
  if (!isEjectedProject(root)) {
    return;
  }
  const pm = await detectProjectPackageManager(root);
  logger.error(
    `This project was ejected to a standalone Astro app, so \`blume ${command}\` would run a regenerated copy of the site instead of it. Run \`${ejectedEquivalent(pm, command)}\` instead.`
  );
  process.exit(1);
};
